name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "your-azure-container-registry"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "your-resource-group"
  CLUSTER_NAME: "your-cluster-name"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"
  LABEL: "test"

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    # runs-on: ["self-hosted", "test-on-aks"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LABEL: [ "engine" ]
    environment: test-on-aks

    # needs: [buildImage]
    steps:
      - uses: actions/checkout@v4
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.sendgrid.net
          # Server port, default 25:
          server_port: 587
            #Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional (recommended) mail server username:
          username: ${{secrets.USER_EMAIL}}
            #Optional (recommended) mail server password:
          password: $ {{secrets.USER_PASSWORD}}
          # Required mail subject:
          subject: GitHub Actions job result
          # Required recipients' addresses:
          to: santhosh.kumar-ext@ab-inbev.com
          # Required sender full name (address can be skipped):
          from: Santhosh # <nikitha.r@ab-inbev.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low

